"""create messages table

Revision ID: 114d955a9263
Revises: 1a90f7a3da81
Create Date: 2015-07-19 11:25:43.494313

"""

# revision identifiers, used by Alembic.
revision = '114d955a9263'
down_revision = '1a90f7a3da81'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum(u'message', u'user_change', u'meta_change', u'ic', u'ooc', u'me', name='messages_type'), nullable=False),
    sa.Column('counter', sa.Integer(), nullable=False),
    sa.Column('color', sa.Unicode(length=6), nullable=False),
    sa.Column('acronym', sa.Unicode(length=15), nullable=False),
    sa.Column('name', sa.Unicode(length=100), nullable=False),
    sa.Column('text', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('messages_log_id', 'messages', ['log_id', 'timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('messages_log_id', table_name='messages')
    op.drop_table('messages')
    ### end Alembic commands ###
