"""ban created

Revision ID: 131dc6a5d6d
Revises: 558083b5d02
Create Date: 2015-11-11 19:01:42.351221

"""

# revision identifiers, used by Alembic.
revision = '131dc6a5d6d'
down_revision = '558083b5d02'
branch_labels = None
depends_on = None

import datetime
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from erigam.lib.model import Ban


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bans', sa.Column('created', sa.DateTime()))

    ban_table = table('bans', column('created'))
    op.execute(ban_table.update().values(created=datetime.datetime.now()))
    op.alter_column('bans', 'created', nullable=False)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bans', 'created')
    ### end Alembic commands ###
