"""create bans table

Revision ID: 1a90f7a3da81
Revises: 
Create Date: 2015-07-12 21:08:02.820670

"""

# revision identifiers, used by Alembic.
revision = '1a90f7a3da81'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('url', sa.String(length=100), nullable=False),
        sa.Column('ip', sa.Unicode(), nullable=False),
        sa.Column('name', sa.Unicode(length=100)),
        sa.Column('counter', sa.Integer()),
        sa.Column('reason', sa.UnicodeText()),
        sa.Column('expires', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['url'], ['logs.url'], ),
        sa.PrimaryKeyConstraint('id', 'url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bans')
    ### end Alembic commands ###
