"""Make bans sequential

Revision ID: 464f3dd0f210
Revises: 
Create Date: 2022-09-09 19:29:49.273825

"""

# revision identifiers, used by Alembic.
revision = '464f3dd0f210'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from sqlalchemy.schema import Sequence, CreateSequence


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(CreateSequence(sa.Sequence('bans_id_seq')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
