"""message admin

Revision ID: 558083b5d02
Revises: 114d955a9263
Create Date: 2015-10-01 20:12:22.419178

"""

# revision identifiers, used by Alembic.
revision = '558083b5d02'
down_revision = '114d955a9263'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'admin')
    ### end Alembic commands ###
